# Generated by Django 5.0.3 on 2024-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='note',
            field=models.CharField(default='Không có', max_length=200),
        ),
    ]
