# Generated by Django 5.0.3 on 2024-09-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismManagement', '0002_tour_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
    ]
