# Generated by Django 5.0.3 on 2024-10-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismManagement', '0003_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourimage',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
