# Generated by Django 5.0.3 on 2024-10-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismManagement', '0005_rename_pay_booking_is_pay'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourcategory',
            table='tour_category',
        ),
    ]
