# Generated by Django 5.0.3 on 2024-10-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismManagement', '0006_alter_tourcategory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='bill',
            table='bill',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='destination',
            table='destination',
        ),
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
        migrations.AlterModelTable(
            name='tour',
            table='tour',
        ),
        migrations.AlterModelTable(
            name='tourimage',
            table='tour_image',
        ),
        migrations.AlterModelTable(
            name='typeofticket',
            table='type_of_ticket',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
