# Generated by Django 5.0.3 on 2024-10-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismManagement', '0007_alter_user_options_alter_bill_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
